/**
 * Intrinio API
 * Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://docs.intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.135.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.intrinioSDK) {
      root.intrinioSDK = {};
    }
    root.intrinioSDK.OptionSurfaceFace = factory(root.intrinioSDK.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OptionSurfaceFace model module.
   * @module model/OptionSurfaceFace
   * @version 7.2.0
   */

  /**
   * Constructs a new <code>OptionSurfaceFace</code>.
   * A triangular face in the options volatility surface.
   * @alias module:model/OptionSurfaceFace
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>OptionSurfaceFace</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OptionSurfaceFace} obj Optional instance to populate.
   * @return {module:model/OptionSurfaceFace} The populated <code>OptionSurfaceFace</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('vertex_a')) {
        obj['vertex_a'] = ApiClient.convertToType(data['vertex_a'], 'Number');
      }
      if (data.hasOwnProperty('vertex_b')) {
        obj['vertex_b'] = ApiClient.convertToType(data['vertex_b'], 'Number');
      }
      if (data.hasOwnProperty('vertex_c')) {
        obj['vertex_c'] = ApiClient.convertToType(data['vertex_c'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The index of vertex A in the vertices array.
   * @member {Number} vertex_a
   */
  exports.prototype['vertex_a'] = undefined;
  /**
   * The index of vertex B in the vertices array.
   * @member {Number} vertex_b
   */
  exports.prototype['vertex_b'] = undefined;
  /**
   * The index of vertex B in the vertices array.
   * @member {Number} vertex_c
   */
  exports.prototype['vertex_c'] = undefined;



  return exports;
}));


