/**
 * Intrinio API
 * Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://docs.intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.122.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.intrinioSDK);
  }
}(this, function(expect, intrinioSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new intrinioSDK.EarningsDateEstimate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EarningsDateEstimate', function() {
    it('should create an instance of EarningsDateEstimate', function() {
      // uncomment below and update the code to test EarningsDateEstimate
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be.a(intrinioSDK.EarningsDateEstimate);
    });

    it('should have the property fiscalYear (base name: "fiscal_year")', function() {
      // uncomment below and update the code to test the property fiscalYear
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

    it('should have the property fiscalPeriod (base name: "fiscal_period")', function() {
      // uncomment below and update the code to test the property fiscalPeriod
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

    it('should have the property expectedDate (base name: "expected_date")', function() {
      // uncomment below and update the code to test the property expectedDate
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

    it('should have the property expected8kAt (base name: "expected_8k_at")', function() {
      // uncomment below and update the code to test the property expected8kAt
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

    it('should have the property historicallyEarliest (base name: "historically_earliest")', function() {
      // uncomment below and update the code to test the property historicallyEarliest
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

    it('should have the property historicallyLatest (base name: "historically_latest")', function() {
      // uncomment below and update the code to test the property historicallyLatest
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

    it('should have the property confidenceIntervals (base name: "confidence_intervals")', function() {
      // uncomment below and update the code to test the property confidenceIntervals
      //var instane = new intrinioSDK.EarningsDateEstimate();
      //expect(instance).to.be();
    });

  });

}));
