/**
 * Intrinio API
 * Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://docs.intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.123.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.intrinioSDK);
  }
}(this, function(expect, intrinioSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new intrinioSDK.ETFNavFlow();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ETFNavFlow', function() {
    it('should create an instance of ETFNavFlow', function() {
      // uncomment below and update the code to test ETFNavFlow
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be.a(intrinioSDK.ETFNavFlow);
    });

    it('should have the property asOfDate (base name: "as_of_date")', function() {
      // uncomment below and update the code to test the property asOfDate
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturnDaily (base name: "nav_return_daily")', function() {
      // uncomment below and update the code to test the property navReturnDaily
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturnOneMonth (base name: "nav_return_one_month")', function() {
      // uncomment below and update the code to test the property navReturnOneMonth
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturnThreeMonth (base name: "nav_return_three_month")', function() {
      // uncomment below and update the code to test the property navReturnThreeMonth
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturnYtd (base name: "nav_return_ytd")', function() {
      // uncomment below and update the code to test the property navReturnYtd
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturnOneYear (base name: "nav_return_one_year")', function() {
      // uncomment below and update the code to test the property navReturnOneYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturn1YearPrior (base name: "nav_return_1_year_prior")', function() {
      // uncomment below and update the code to test the property navReturn1YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturn2YearPrior (base name: "nav_return_2_year_prior")', function() {
      // uncomment below and update the code to test the property navReturn2YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturn3YearPrior (base name: "nav_return_3_year_prior")', function() {
      // uncomment below and update the code to test the property navReturn3YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturn4YearPrior (base name: "nav_return_4_year_prior")', function() {
      // uncomment below and update the code to test the property navReturn4YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navReturn5YearPrior (base name: "nav_return_5_year_prior")', function() {
      // uncomment below and update the code to test the property navReturn5YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navAnnualizedReturnThreeYear (base name: "nav_annualized_return_three_year")', function() {
      // uncomment below and update the code to test the property navAnnualizedReturnThreeYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navAnnualizedReturnFiveYear (base name: "nav_annualized_return_five_year")', function() {
      // uncomment below and update the code to test the property navAnnualizedReturnFiveYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navAnnualizedReturnTenYear (base name: "nav_annualized_return_ten_year")', function() {
      // uncomment below and update the code to test the property navAnnualizedReturnTenYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navAnnualizedReturnInception (base name: "nav_annualized_return_inception")', function() {
      // uncomment below and update the code to test the property navAnnualizedReturnInception
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navUnadjusted (base name: "nav_unadjusted")', function() {
      // uncomment below and update the code to test the property navUnadjusted
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navSplitAdjusted (base name: "nav_split_adjusted")', function() {
      // uncomment below and update the code to test the property navSplitAdjusted
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property navSplitDividendAdjusted (base name: "nav_split_dividend_adjusted")', function() {
      // uncomment below and update the code to test the property navSplitDividendAdjusted
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsDaily (base name: "net_flows_daily")', function() {
      // uncomment below and update the code to test the property netFlowsDaily
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsOneMonth (base name: "net_flows_one_month")', function() {
      // uncomment below and update the code to test the property netFlowsOneMonth
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsThreeMonth (base name: "net_flows_three_month")', function() {
      // uncomment below and update the code to test the property netFlowsThreeMonth
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsYtd (base name: "net_flows_ytd")', function() {
      // uncomment below and update the code to test the property netFlowsYtd
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsOneYear (base name: "net_flows_one_year")', function() {
      // uncomment below and update the code to test the property netFlowsOneYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsThreeYear (base name: "net_flows_three_year")', function() {
      // uncomment below and update the code to test the property netFlowsThreeYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsFiveYear (base name: "net_flows_five_year")', function() {
      // uncomment below and update the code to test the property netFlowsFiveYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsTenYear (base name: "net_flows_ten_year")', function() {
      // uncomment below and update the code to test the property netFlowsTenYear
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlows1YearPrior (base name: "net_flows_1_year_prior")', function() {
      // uncomment below and update the code to test the property netFlows1YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlows2YearPrior (base name: "net_flows_2_year_prior")', function() {
      // uncomment below and update the code to test the property netFlows2YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlows3YearPrior (base name: "net_flows_3_year_prior")', function() {
      // uncomment below and update the code to test the property netFlows3YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlows4YearPrior (base name: "net_flows_4_year_prior")', function() {
      // uncomment below and update the code to test the property netFlows4YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlows5YearPrior (base name: "net_flows_5_year_prior")', function() {
      // uncomment below and update the code to test the property netFlows5YearPrior
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property netFlowsInception (base name: "net_flows_inception")', function() {
      // uncomment below and update the code to test the property netFlowsInception
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property shareOutstandingUnadjusted (base name: "share_outstanding_unadjusted")', function() {
      // uncomment below and update the code to test the property shareOutstandingUnadjusted
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property shareOutstandingSplitAdjusted (base name: "share_outstanding_split_adjusted")', function() {
      // uncomment below and update the code to test the property shareOutstandingSplitAdjusted
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

    it('should have the property totalNetAssets (base name: "total_net_assets")', function() {
      // uncomment below and update the code to test the property totalNetAssets
      //var instane = new intrinioSDK.ETFNavFlow();
      //expect(instance).to.be();
    });

  });

}));
