/**
 * Intrinio API
 * Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.intrinioSDK);
  }
}(this, function(expect, intrinioSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new intrinioSDK.CryptoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CryptoApi', function() {
    describe('getCryptoBookAsks', function() {
      it('should call getCryptoBookAsks successfully', function(done) {
        //uncomment below and update the code to test getCryptoBookAsks
        //instance.getCryptoBookAsks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoBookBids', function() {
      it('should call getCryptoBookBids successfully', function(done) {
        //uncomment below and update the code to test getCryptoBookBids
        //instance.getCryptoBookBids(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoBookSummary', function() {
      it('should call getCryptoBookSummary successfully', function(done) {
        //uncomment below and update the code to test getCryptoBookSummary
        //instance.getCryptoBookSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoCurrencies', function() {
      it('should call getCryptoCurrencies successfully', function(done) {
        //uncomment below and update the code to test getCryptoCurrencies
        //instance.getCryptoCurrencies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoExchanges', function() {
      it('should call getCryptoExchanges successfully', function(done) {
        //uncomment below and update the code to test getCryptoExchanges
        //instance.getCryptoExchanges(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoPairs', function() {
      it('should call getCryptoPairs successfully', function(done) {
        //uncomment below and update the code to test getCryptoPairs
        //instance.getCryptoPairs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoPrices', function() {
      it('should call getCryptoPrices successfully', function(done) {
        //uncomment below and update the code to test getCryptoPrices
        //instance.getCryptoPrices(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoSnapshot', function() {
      it('should call getCryptoSnapshot successfully', function(done) {
        //uncomment below and update the code to test getCryptoSnapshot
        //instance.getCryptoSnapshot(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCryptoStats', function() {
      it('should call getCryptoStats successfully', function(done) {
        //uncomment below and update the code to test getCryptoStats
        //instance.getCryptoStats(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
